In [179]:
import pandas as pd
import numpy as np
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [120]:
second_table = pd.read_csv('C:/Users/TArs/Desktop/проект Akima/transfer_attributes_change-main/data replaced/Kolya_prediction.csv')
second_table

,position,sca_per90_y,gca_per90_y,npxg_xa_per90_y,passes_progressive_distance_y,passes_into_penalty_area_y,passes_completed_y,npxg_per90_y,shots_total_per90_y,dribbles_completed_pct_y,crosses_y,carry_progressive_distance_y,aerials_won_y,tackles_won_y,interceptions_y
0,CB,0.278565,1.024986,0.595331,0.140661,0.680888,0.143438,0.656569,0.597862,0.274126,0.617806,0.235940,0.218219,0.330069,0.393571
1,FB,0.296864,0.415100,0.294290,0.244496,0.403616,0.171853,0.574721,0.375751,0.087164,0.519230,0.194451,0.369321,0.361341,0.322995
2,MID,0.339216,0.682346,0.434283,0.272478,0.397855,0.223462,0.423992,0.256054,0.296334,0.543675,0.339018,0.497185,0.273874,0.368934
3,ST,0.340079,0.512122,0.315257,0.520648,0.475254,0.183216,0.388166,0.305346,0.213966,0.579865,0.646945,0.534843,0.359897,0.621178
4,WIN,0.223975,0.475328,0.304001,0.388123,0.348424,0.190393,0.415069,0.373914,0.163974,0.486006,0.302300,0.442835,0.470102,0.509057
5,all,0.313073,0.606854,0.364310,0.494154,0.469907,0.190858,0.503615,0.373575,0.360042,0.535061,0.388798,0.423496,0.368192,0.442850

In [121]:
third_table = pd.read_csv('C:/Users/TArs/Desktop/проект Akima/transfer_attributes_change-main/data replaced/Sanya prediction.csv')
third_table = third_table.rename(columns={'Unnamed: 0': 'position'})
mapping = {'Centerbacks':'CB','Midfielders':'MID','Wingers':'WIN', 'Forwards' : 'ST', 'Fullbacks' : 'FB'}
third_table['position'] = third_table['position'].map(mapping)
third_table

,position,sca_per90_y,gca_per90_y,npxg_xa_per90_y,passes_progressive_distance_y,passes_into_penalty_area_y,passes_completed_y,npxg_per90_y,shots_total_per90_y,dribbles_completed_pct_y,crosses_y,carry_progressive_distance_y,aerials_won_y,tackles_won_y,interceptions_y
0,CB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.444826,0.426283,0.570315
1,MID,0.365005,0.925911,0.513973,0.388074,0.476056,0.372991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,WIN,0.282728,0.496310,NaN,NaN,NaN,NaN,NaN,NaN,0.168855,0.596257,0.621595,NaN,NaN,NaN
3,ST,0.426603,0.689448,NaN,NaN,NaN,NaN,0.497541,0.296662,NaN,NaN,NaN,NaN,NaN,NaN
4,FB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.476164,NaN,NaN,0.454195,0.533850

In [152]:
path_to_Kolya_folder = "C:/Users/TArs/Desktop/проект Akima/transfer_attributes_change-main/data replaced/first_prediction"
path_to_Sanya_folder = "C:/Users/TArs/Desktop/проект Akima/transfer_attributes_change-main/data replaced/second_prediction"
mid_featch = ['sca_per90_y', 'gca_per90_y', 'npxg_xa_per90_y','passes_progressive_distance_y',
'passes_into_penalty_area_y', 'passes_completed_y']
fwd_featch = [ 'sca_per90_y', 'gca_per90_y', 'npxg_per90_y','shots_total_per90_y']
win_featch = [ 'sca_per90_y', 'gca_per90_y', 'dribbles_completed_pct_y','crosses_y','carry_progressive_distance_y']
cb_featch = ['aerials_won_y', 'tackles_won_y','interceptions_y']
fb_featch = ['tackles_won_y', 'crosses_y', 'interceptions_y']
#all_featch = [ 'sca_per90_y', 'gca_per90_y', 'npxg_xa_per90_y','passes_progressive_distance_y',
#'passes_into_penalty_area_y', 'passes_completed_y', 'npxg_per90_y','shots_total_per90_y', 'dribbles_completed_pct_y','crosses_y','carry_progressive_distance_y', 
#'aerials_won_y', 'tackles_won_y','interceptions_y']
player_position = ['MID', 'ST', 'WIN', 'CB', 'FB']
coefficients_val = {}


def average_error(featch, pos, df):
    temp = []
    for i in featch:
            temp.extend(list(df[df['position'] == pos][i]))
    average_error = np.array(temp).mean()
    return average_error

def final_prediction(coefs, pos):
    temp = coefs[pos]
    if pos == 'CB':
        df2 = pd.read_csv(path_to_Kolya_folder + '/CB.csv')
        df3 = pd.read_csv(path_to_Sanya_folder + '/CB.csv')
    elif pos == 'MID':
        df2 = pd.read_csv(path_to_Kolya_folder + '/MID.csv')
        df3 = pd.read_csv(path_to_Sanya_folder + '/MID.csv')
    elif pos == 'ST':
        df2 = pd.read_csv(path_to_Kolya_folder + '/ST.csv')
        df3 = pd.read_csv(path_to_Sanya_folder + '/ST.csv')
    elif pos == 'WIN':
        df2 = pd.read_csv(path_to_Kolya_folder + '/WIN.csv')
        df3 = pd.read_csv(path_to_Sanya_folder + '/WIN.csv')
    elif pos == 'FB':
        df2 = pd.read_csv(path_to_Kolya_folder + '/FB.csv')
        df3 = pd.read_csv(path_to_Sanya_folder + '/FB.csv')
    df2 *= temp[0]
    df3 *= temp[1]
    res = df2 + df3
    return res

def average_model(number):
    temp = {}
    if number == 2:
        table = second_table
    elif number == 3:
        table = third_table
    for i in player_position:
        if i == 'CB':
            featches = cb_featch
        elif i == 'FB':
            featches = fb_featch
        elif i == 'ST':
            featches = fwd_featch
        elif i == 'WIN':
            featches = win_featch
        elif i == 'MID':
            featches = mid_featch
        temp[i] = 1/average_error(featches, i, table)
    return temp

In [153]:
#second_average_mid_val = average_error(mid_featch, 'MID', second_table)
#second_average_fwd_val = average_error(fwd_featch, 'ST', second_table)
#second_average_win_val = average_error(win_featch, 'WIN', second_table)
#second_average_cb_val = average_error(cb_featch, 'CB', second_table)
#second_average_fb_val = average_error(fb_featch, 'FB', second_table)
#second_average_all_val = average_error(all_featch, 'all', second_table)
#second_model_val = {"MID": 1/second_average_mid_val, "ST": 1/second_average_fwd_val, "WIN": 1/second_average_win_val, "CB": 1/second_average_cb_val, "FB": 1/second_average_fb_val}
second_model_val = average_model(2)
second_model_val

{'MID': 2.5535825788027102,
 'ST': 2.5878039706353198,
 'WIN': 3.027398416387943,
 'CB': 3.1851902440785644,
 'FB': 2.492592825643839}

In [154]:
#third_average_mid_val = average_error(mid_featch, 'MID', third_table)
#third_average_fwd_val = average_error(fwd_featch, 'ST', third_table)
#third_average_win_val = average_error(win_featch, 'WIN', third_table)
#third_average_cb_val = average_error(cb_featch, 'CB', third_table)
#third_average_fb_val = average_error(fb_featch, 'FB', third_table)
#third_model_val = {"MID": 1/third_average_mid_val, "ST": 1/third_average_fwd_val, "WIN": 1/third_average_win_val, "CB": 1/third_average_cb_val, "FB": 1/third_average_fb_val}
third_model_val = average_model(3)
third_model_val

{'MID': 1.9723798080731156,
 'ST': 2.0939614244339606,
 'WIN': 2.3086748534513646,
 'CB': 2.0812763276918314,
 'FB': 2.0488877179533187}

Coefs for each model

In [177]:
for i in player_position:
        coefficients_val[i] = []
        sum = second_model_val[i] + third_model_val[i]
        coefficients_val[i].append(second_model_val[i] / sum)
        coefficients_val[i].append(third_model_val[i] / sum)
        print(i + ':')
        print('first_model_coef = ' + str(coefficients_val[i][0]))
        print('second_model_coef = ' + str(coefficients_val[i][1]))
        print()

MID:
first_model_coef = 0.5642076448110727
second_model_coef = 0.43579235518892745

ST:
first_model_coef = 0.5527410607461729
second_model_coef = 0.4472589392538269

WIN:
first_model_coef = 0.567345735955217
second_model_coef = 0.4326542640447831

CB:
first_model_coef = 0.6048059359480219
second_model_coef = 0.3951940640519781

FB:
first_model_coef = 0.5488502706805692
second_model_coef = 0.45114972931943065

Parsing prediction tables from models to make final predict

In [146]:
#table = pd.read_csv('C:/Users/TArs/Desktop/проект Akima/transfer_attributes_change-main/data replaced/pred_WIN.csv')
#table.to_csv(r'C:\Users\TArs\Desktop\проект Akima\transfer_attributes_change-main\data replaced\WIN_1.csv', index = False)
first_mid_table = pd.read_csv('C:/Users/TArs/Desktop/проект Akima/transfer_attributes_change-main/data replaced/Kolya`s prediction/ST.csv')
first_mid_table = first_mid_table.drop('Unnamed: 0', 1)
first_mid_table = first_mid_table.drop(first_mid_table[first_mid_table.index > 13].index)
first_mid_table.to_csv(r'C:\Users\TArs\Desktop\проект Akima\transfer_attributes_change-main\data replaced\first_prediction\ST.csv', index = False)
first_mid_table

    sca_per90_y  gca_per90_y  npxg_per90_y  shots_total_per90_y
0        1.9541     0.358023      0.414037             2.155125
1        1.8848     0.231823      0.273148             2.078997
2        1.9100     0.239777      0.300503             2.155463
3        1.9172     0.249125      0.282093             2.052397
4        1.9100     0.209308      0.249847             2.116124
5        1.9256     0.262386      0.263298             2.064578
6        1.9151     0.295462      0.287618             2.067594
7        1.9019     0.304571      0.435705             2.099729
8        1.9334     0.382840      0.330666             2.107549
9        1.9295     0.329093      0.359475             2.149633
10       1.9244     0.321363      0.421824             2.142532
11       1.9223     0.308471      0.266428             2.070478
12       1.9106     0.331906      0.306725             2.096480
13       1.9106     0.311787      0.349365             2.090351

# Predictions

MID prediction

In [149]:
MID_table = final_prediction(coefficients_val, 'MID')
MID_table

,sca_per90_y,gca_per90_y,npxg_xa_per90_y,passes_progressive_distance_y,passes_into_penalty_area_y,passes_completed_y
0,1.844060,0.139861,0.140689,558.815382,2.413916,148.480487
1,2.332697,0.229105,0.178829,451.960412,2.067629,66.794201
2,1.762102,0.116497,0.110664,871.664404,1.674731,161.993813
3,1.603057,0.133465,0.129039,323.204409,1.299766,71.464608
4,2.158849,0.200556,0.125559,1307.147959,4.069960,286.677091
5,1.907238,0.198219,0.148144,586.404768,2.030594,118.952956
6,2.256087,0.225626,0.143638,707.376669,5.427332,251.209494
7,2.082176,0.143986,0.138014,1012.775125,3.198490,219.694205
8,1.708409,0.161656,0.123269,517.578024,1.772467,98.550903
9,1.733634,0.151110,0.130789,632.776862,2.561156,144.073032
10,1.622656,0.145741,0.076970,700.797273,2.145453,172.293627
11,2.291718,0.177350,0.167373,1197.926718,1.145831,296.640707
12,2.079542,0.183076,0.073498,746.955804,3.137532,215.975082
13,1.618404,0.189212,0.131208,388.867072,1.490763,70.184378

CB prediction

In [184]:
CB_table = final_prediction(coefficients_val, 'CB')
CB_table

    aerials_won_y  tackles_won_y  interceptions_y
0        5.624483       2.412095         5.549420
1       21.496961       6.969952         9.246682
2       22.634033       8.780277        16.503075
3        7.539091       1.611445         3.437691
4       10.995596       3.608050         2.767375
5        7.870789       2.919696         3.666368
6        7.470921       3.137503         2.044271
7        6.760955       1.898164         4.361979
8        8.905422       2.094562         2.992162
9       19.108421       4.897323         2.617990
10      16.022181       4.677413        13.051515
11       7.732986       2.794761         0.995307
12       8.575050       3.314221         7.773701
13      16.241589       3.694822         4.536854

FB predict

In [185]:
FB_table = final_prediction(coefficients_val, 'FB')
FB_table

    tackles_won_y  crosses_y  interceptions_y
0        9.767150  14.523960         8.938293
1        8.768524  11.918743         7.473125
2        7.146784  13.471952         6.289012
3        6.764058  10.045942         3.700024
4       10.928852  15.159717         6.918201
5        8.586455   9.904695         7.888929
6       12.904171  13.864518         9.591360
7        7.949513  13.521436         7.586309
8        5.923257   9.688780         3.505784
9        9.237147  12.171970         9.531447
10       6.824803   8.696705         4.433782
11       6.648096   6.609753         6.400064
12       6.680098  10.752193         7.590093
13       4.179281   4.057667         5.975140

WIN predict

In [186]:
WIN_table = final_prediction(coefficients_val, 'WIN')
WIN_table

,sca_per90_y,gca_per90_y,dribbles_completed_pct_y,crosses_y,carry_progressive_distance_y
0,3.352974,0.431755,54.396461,2.779418,301.791750
1,2.913692,0.296933,52.582173,7.904333,512.450008
2,2.953412,0.322853,52.917204,19.164417,600.030753
3,2.747854,0.287965,53.659137,17.426880,674.416749
4,2.081904,0.227472,53.241677,9.841135,427.935698
5,3.190862,0.438091,52.370233,5.186454,415.797878
6,3.566990,0.262600,54.816656,8.509786,618.089096
7,2.976826,0.422095,53.703857,3.022487,352.188308
8,2.848681,0.392745,52.037401,4.373208,458.795413
9,2.683596,0.277976,55.654254,3.899616,263.285989
10,2.542280,0.326975,54.342956,3.854849,304.886894
11,2.813671,0.299160,54.862510,8.919631,330.928471
12,2.041924,0.238379,55.138084,2.582653,290.008219
13,2.209281,0.250492,53.429474,5.467243,487.454718

ST predict

In [187]:
ST_table = final_prediction(coefficients_val, 'ST')
ST_table

    sca_per90_y  gca_per90_y  npxg_per90_y  shots_total_per90_y
0      1.945412     0.294912      0.464074             2.701150
1      1.630304     0.217735      0.275078             1.848800
2      2.063945     0.240369      0.288273             2.189092
3      1.860394     0.285881      0.204939             1.820821
4      2.030403     0.222797      0.252672             1.890966
5      1.644711     0.211648      0.201212             1.942952
6      1.933182     0.282117      0.273947             1.775806
7      2.063448     0.330879      0.391422             2.520967
8      1.786537     0.335369      0.330524             2.503227
9      1.985735     0.288768      0.328743             2.327871
10     2.251031     0.289932      0.398577             2.007204
11     1.936334     0.287378      0.205057             2.051782
12     1.922675     0.285555      0.280433             2.106795
13     1.665689     0.307122      0.331221             2.234212